################################################################################
# Sample Contao Web application
# running Apache 2, php 7.1 FPM and mariadb all linked together anbd ready 2 use
################################################################################
version: '2'
services:
  web:
    image: ctsmedia/baseimage-web-apache:1.2.0
    container_name: contao_phpbb_bridge
    environment:
      PROJECT_NAME: &project contao
      PHPFPM_HOST: &phpfpm_host php
      DEFAULT_PASSWORD: &password contaodocker
      DOCROOT: web
    volumes_from:
      - php
    depends_on:
      - db
      - php
    ports:
        - "80:80"
  php:
    image: ctsmedia/contao-phpbb-bridge:latest
    container_name: contao_phpbb_bridge_php
    environment:
      DEFAULT_PASSWORD: *password
      PROJECT_NAME: *project
    ports:
      - "9000"
    volumes:
      - /var/www/share/project

      #This is what you want in general. You local source directly mounted into the vendor folder
      - .:/var/www/share/project/vendor/ctsmedia/contao-phpbb-bridge-bundle

      # Use this if you need composer related changes (like extra section to be reloaded)
      # then remove in container the dep and set it new with a path repos set
      #- .:/var/www/share/contao-phpbb-bridge-bundle
  db:
    image: mariadb:10.1
    container_name: contao_phpbb_bridge_db
    environment:
      MYSQL_ROOT_PASSWORD: *password
      MYSQL_DATABASE: *project
      MYSQL_USER: *project
      MYSQL_PASSWORD: *project
