ctsmedia_contaophpbbbridge_controller_is_valid_login:
        path: /contao_connect/is_valid_login/{username}/{password}
        defaults: { _controller: ctsmedia.contaophpbbbridge.controller:isValidLogin }
ctsmedia_contaophpbbbridge_controller_purge_cache:
        path: /contao_connect/purge_cache
        defaults: { _controller: ctsmedia.contaophpbbbridge.controller:purgeCache }
ctsmedia_contaophpbbbridge_controller_test:
        path: /contao_connect/test
        defaults: { _controller: ctsmedia.contaophpbbbridge.controller:test }