imports:
    - { resource: contao.yml }

services:
    ctsmedia.contaophpbbbridge.connector:
        class: ctsmedia\contaophpbbbridge\contao\Connector
        arguments:
            - '%contao.forum_pageId%'
            - '%contao.url%'
            - '@user'
            - '@auth'
            - '@request'
    ctsmedia.contaophpbbbridge.theme_listener:
        class: ctsmedia\contaophpbbbridge\event\ThemeListener
        arguments:
            - %core.root_path%
            - @template
            - @ctsmedia.contaophpbbbridge.connector
            - {body_class: '%contao.body_class%', forum_pageUrl: '%contao.forum_pageUrl%', load_dynamic_layout: '%contao.load_dynamic_layout%'}
        tags:
            - { name: event.listener }
    ctsmedia.contaophpbbbridge.controller:
        class: ctsmedia\contaophpbbbridge\controller\Connect
        arguments:
            - @config
            - @service_container
            - @dispatcher
            - @user
            - @ctsmedia.contaophpbbbridge.connector
            - %core.root_path%
            - %core.php_ext%
    auth.provider.contao:
        class: ctsmedia\contaophpbbbridge\contao\AuthProvider
        arguments:
            - @dbal.conn
            - @config
            - @passwords.manager
            - @request
            - @user
            - @service_container
            - %core.root_path%
            - %core.php_ext%
            - @ctsmedia.contaophpbbbridge.connector
        tags:
            - { name: auth.provider }